'use client';

import { createContext, useContext, useState, ReactNode, useEffect } from 'react';

// 使用完整语言名称作为类型
type Language = 'Chinese' | 'English' | 'French' | 'Spanish' | 'Japanese' | 'German' | 'Russian' | 'Arabic';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  getLanguageName: (lang: Language) => string;
}

// 语言列表
export const LANGUAGES: { code: Language; name: string; flag: string }[] = [
  { code: 'Chinese', name: '中文', flag: '🇨🇳' },
  { code: 'English', name: 'English', flag: '🇬🇧' },
  { code: 'French', name: 'Français', flag: '🇫🇷' },
  { code: 'Spanish', name: 'Español', flag: '🇪🇸' },
  { code: 'Japanese', name: '日本語', flag: '🇯🇵' },
  { code: 'German', name: 'Deutsch', flag: '🇩🇪' },
  { code: 'Russian', name: 'Русский', flag: '🇷🇺' },
  { code: 'Arabic', name: 'العربية', flag: '🇸🇦' },
];

// 翻译字典
const translations: Record<Language, Record<string, string>> = {
  Chinese: {
    'dashboard': '仪表盘',
    'log_dive': '记录潜水',
    'journal': '潜水日记',
    'map': '潜点地图',
    'profile': '个人资料',
    'photos': '照片墙',
    'logout': '退出',
    'welcome_back': '欢迎回来',
    'total_dives': '总潜水次数',
    'total_time': '总潜水时间',
    'max_depth': '最大深度',
    'avg_air': '平均耗气率',
    'recent_dives': '最近潜水记录',
    'no_dives': '还没有潜水记录',
    'log_first_dive': '记录第一次潜水',
    'login': '登录',
    'register': '注册',
    'email': '邮箱',
    'password': '密码',
    'confirm_password': '确认密码',
    'username': '用户名',
    'already_have_account': '已有账户？',
    'no_account': '还没有账户？',
    'login_failed': '登录失败',
    'register_failed': '注册失败',
    'log_dive_title': '记录潜水',
    'dive_site': '潜点',
    'dive_type': '潜水类型',
    'date': '日期',
    'buddy': '潜伴',
    'depth': '深度',
    'duration': '时长',
    'temperature': '水温',
    'visibility': '能见度',
    'weight': '配重',
    'notes': '备注',
    'rating': '评分',
    'save': '保存',
    'cancel': '取消',
    'dive_sites': '潜水目的地',
    'view_all': '查看全部',
    'collapse': '收起',
    'view_on_google_maps': '在 Google Maps 打开',
    'click_to_view': '点击查看位置',
    'loading': '加载中...',
    'error': '错误',
    'success': '成功',
    'save_success': '保存成功',
  },
  English: {
    'dashboard': 'Dashboard',
    'log_dive': 'Log Dive',
    'journal': 'Dive Journal',
    'map': 'Dive Map',
    'profile': 'Profile',
    'photos': 'Photos',
    'logout': 'Logout',
    'welcome_back': 'Welcome Back',
    'total_dives': 'Total Dives',
    'total_time': 'Total Bottom Time',
    'max_depth': 'Max Depth',
    'avg_air': 'Avg Air Consumption',
    'recent_dives': 'Recent Dives',
    'no_dives': 'No dives yet',
    'log_first_dive': 'Log Your First Dive',
    'login': 'Login',
    'register': 'Register',
    'email': 'Email',
    'password': 'Password',
    'confirm_password': 'Confirm Password',
    'username': 'Username',
    'already_have_account': 'Already have an account?',
    'no_account': "Don't have an account?",
    'login_failed': 'Login failed',
    'register_failed': 'Registration failed',
    'log_dive_title': 'Log a Dive',
    'dive_site': 'Dive Site',
    'dive_type': 'Dive Type',
    'date': 'Date',
    'buddy': 'Buddy',
    'depth': 'Depth',
    'duration': 'Duration',
    'temperature': 'Temperature',
    'visibility': 'Visibility',
    'weight': 'Weight',
    'notes': 'Notes',
    'rating': 'Rating',
    'save': 'Save',
    'cancel': 'Cancel',
    'dive_sites': 'Dive Sites',
    'view_all': 'View All',
    'collapse': 'Collapse',
    'view_on_google_maps': 'View on Google Maps',
    'click_to_view': 'Click to view location',
    'loading': 'Loading...',
    'error': 'Error',
    'success': 'Success',
    'save_success': 'Saved successfully',
  },
  French: {
    'dashboard': 'Tableau de bord',
    'log_dive': 'Enregistrer une plongée',
    'journal': 'Journal de plongée',
    'map': 'Carte des sites',
    'profile': 'Profil',
    'photos': 'Photos',
    'logout': 'Déconnexion',
    'welcome_back': 'Bon retour',
    'total_dives': 'Total des plongées',
    'total_time': 'Temps total sous l\'eau',
    'max_depth': 'Profondeur max',
    'avg_air': 'Consommation moyenne',
    'recent_dives': 'Plongées récentes',
    'no_dives': 'Aucune plongée',
    'log_first_dive': 'Enregistrer votre première plongée',
    'login': 'Connexion',
    'register': 'Inscription',
    'email': 'Email',
    'password': 'Mot de passe',
    'confirm_password': 'Confirmer le mot de passe',
    'username': 'Nom d\'utilisateur',
    'already_have_account': 'Déjà un compte ?',
    'no_account': 'Pas encore de compte ?',
    'login_failed': 'Échec de la connexion',
    'register_failed': 'Échec de l\'inscription',
    'log_dive_title': 'Enregistrer une plongée',
    'dive_site': 'Site de plongée',
    'dive_type': 'Type de plongée',
    'date': 'Date',
    'buddy': 'Binôme',
    'depth': 'Profondeur',
    'duration': 'Durée',
    'temperature': 'Température',
    'visibility': 'Visibilité',
    'weight': 'Lest',
    'notes': 'Notes',
    'rating': 'Évaluation',
    'save': 'Enregistrer',
    'cancel': 'Annuler',
    'dive_sites': 'Sites de plongée',
    'view_all': 'Voir tout',
    'collapse': 'Réduire',
    'view_on_google_maps': 'Voir sur Google Maps',
    'click_to_view': 'Cliquez pour voir l\'emplacement',
    'loading': 'Chargement...',
    'error': 'Erreur',
    'success': 'Succès',
    'save_success': 'Enregistré avec succès',
  },
  Spanish: {
    'dashboard': 'Panel de control',
    'log_dive': 'Registrar inmersión',
    'journal': 'Diario de buceo',
    'map': 'Mapa de sitios',
    'profile': 'Perfil',
    'photos': 'Fotos',
    'logout': 'Cerrar sesión',
    'welcome_back': 'Bienvenido de nuevo',
    'total_dives': 'Total de inmersiones',
    'total_time': 'Tiempo total',
    'max_depth': 'Profundidad máxima',
    'avg_air': 'Consumo medio de aire',
    'recent_dives': 'Inmersiones recientes',
    'no_dives': 'Sin inmersiones',
    'log_first_dive': 'Registra tu primera inmersión',
    'login': 'Iniciar sesión',
    'register': 'Registrarse',
    'email': 'Correo electrónico',
    'password': 'Contraseña',
    'confirm_password': 'Confirmar contraseña',
    'username': 'Nombre de usuario',
    'already_have_account': '¿Ya tienes cuenta?',
    'no_account': '¿No tienes cuenta?',
    'login_failed': 'Error de inicio de sesión',
    'register_failed': 'Error de registro',
    'log_dive_title': 'Registrar una inmersión',
    'dive_site': 'Sitio de buceo',
    'dive_type': 'Tipo de buceo',
    'date': 'Fecha',
    'buddy': 'Compañero',
    'depth': 'Profundidad',
    'duration': 'Duración',
    'temperature': 'Temperatura',
    'visibility': 'Visibilidad',
    'weight': 'Peso',
    'notes': 'Notas',
    'rating': 'Valoración',
    'save': 'Guardar',
    'cancel': 'Cancelar',
    'dive_sites': 'Sitios de buceo',
    'view_all': 'Ver todo',
    'collapse': 'Colapsar',
    'view_on_google_maps': 'Ver en Google Maps',
    'click_to_view': 'Haz clic para ver la ubicación',
    'loading': 'Cargando...',
    'error': 'Error',
    'success': 'Éxito',
    'save_success': 'Guardado con éxito',
  },
  Japanese: {
    'dashboard': 'ダッシュボード',
    'log_dive': 'ダイブログ',
    'journal': 'ダイブジャーナル',
    'map': 'ダイブマップ',
    'profile': 'プロフィール',
    'photos': '写真',
    'logout': 'ログアウト',
    'welcome_back': 'おかえりなさい',
    'total_dives': '総ダイブ数',
    'total_time': '総潜水時間',
    'max_depth': '最大深度',
    'avg_air': '平均空気消費量',
    'recent_dives': '最近のダイブ',
    'no_dives': 'まだダイブがありません',
    'log_first_dive': '最初のダイブを記録',
    'login': 'ログイン',
    'register': '登録',
    'email': 'メールアドレス',
    'password': 'パスワード',
    'confirm_password': 'パスワード確認',
    'username': 'ユーザー名',
    'already_have_account': 'アカウントをお持ちですか？',
    'no_account': 'アカウントをお持ちでない方',
    'login_failed': 'ログインに失敗しました',
    'register_failed': '登録に失敗しました',
    'log_dive_title': 'ダイブを記録',
    'dive_site': 'ダイブサイト',
    'dive_type': 'ダイブタイプ',
    'date': '日付',
    'buddy': 'バディ',
    'depth': '深度',
    'duration': '時間',
    'temperature': '水温',
    'visibility': '透明度',
    'weight': 'ウェイト',
    'notes': 'メモ',
    'rating': '評価',
    'save': '保存',
    'cancel': 'キャンセル',
    'dive_sites': 'ダイブサイト',
    'view_all': 'すべて表示',
    'collapse': '折りたたむ',
    'view_on_google_maps': 'Googleマップで見る',
    'click_to_view': 'クリックして場所を表示',
    'loading': '読み込み中...',
    'error': 'エラー',
    'success': '成功',
    'save_success': '保存しました',
  },
  German: {
    'dashboard': 'Dashboard',
    'log_dive': 'Tauchgang protokollieren',
    'journal': 'Tauchjournal',
    'map': 'Tauchkarte',
    'profile': 'Profil',
    'photos': 'Fotos',
    'logout': 'Abmelden',
    'welcome_back': 'Willkommen zurück',
    'total_dives': 'Gesamttauchgänge',
    'total_time': 'Gesamtzeit unter Wasser',
    'max_depth': 'Maximale Tiefe',
    'avg_air': 'Durchschnittlicher Luftverbrauch',
    'recent_dives': 'Letzte Tauchgänge',
    'no_dives': 'Keine Tauchgänge',
    'log_first_dive': 'Ersten Tauchgang protokollieren',
    'login': 'Anmelden',
    'register': 'Registrieren',
    'email': 'E-Mail',
    'password': 'Passwort',
    'confirm_password': 'Passwort bestätigen',
    'username': 'Benutzername',
    'already_have_account': 'Bereits ein Konto?',
    'no_account': 'Noch kein Konto?',
    'login_failed': 'Anmeldung fehlgeschlagen',
    'register_failed': 'Registrierung fehlgeschlagen',
    'log_dive_title': 'Tauchgang protokollieren',
    'dive_site': 'Tauchplatz',
    'dive_type': 'Tauchtyp',
    'date': 'Datum',
    'buddy': 'Buddy',
    'depth': 'Tiefe',
    'duration': 'Dauer',
    'temperature': 'Temperatur',
    'visibility': 'Sichtweite',
    'weight': 'Gewicht',
    'notes': 'Notizen',
    'rating': 'Bewertung',
    'save': 'Speichern',
    'cancel': 'Abbrechen',
    'dive_sites': 'Tauchplätze',
    'view_all': 'Alle anzeigen',
    'collapse': 'Einklappen',
    'view_on_google_maps': 'Auf Google Maps anzeigen',
    'click_to_view': 'Klicken, um Ort anzuzeigen',
    'loading': 'Laden...',
    'error': 'Fehler',
    'success': 'Erfolg',
    'save_success': 'Erfolgreich gespeichert',
  },
  Russian: {
    'dashboard': 'Панель управления',
    'log_dive': 'Записать погружение',
    'journal': 'Журнал погружений',
    'map': 'Карта дайв-сайтов',
    'profile': 'Профиль',
    'photos': 'Фото',
    'logout': 'Выйти',
    'welcome_back': 'С возвращением',
    'total_dives': 'Всего погружений',
    'total_time': 'Общее время под водой',
    'max_depth': 'Максимальная глубина',
    'avg_air': 'Средний расход воздуха',
    'recent_dives': 'Недавние погружения',
    'no_dives': 'Нет погружений',
    'log_first_dive': 'Записать первое погружение',
    'login': 'Войти',
    'register': 'Зарегистрироваться',
    'email': 'Эл. почта',
    'password': 'Пароль',
    'confirm_password': 'Подтвердить пароль',
    'username': 'Имя пользователя',
    'already_have_account': 'Уже есть аккаунт?',
    'no_account': 'Нет аккаунта?',
    'login_failed': 'Ошибка входа',
    'register_failed': 'Ошибка регистрации',
    'log_dive_title': 'Записать погружение',
    'dive_site': 'Место погружения',
    'dive_type': 'Тип погружения',
    'date': 'Дата',
    'buddy': 'Напарник',
    'depth': 'Глубина',
    'duration': 'Продолжительность',
    'temperature': 'Температура',
    'visibility': 'Видимость',
    'weight': 'Вес',
    'notes': 'Заметки',
    'rating': 'Рейтинг',
    'save': 'Сохранить',
    'cancel': 'Отмена',
    'dive_sites': 'Места для дайвинга',
    'view_all': 'Показать все',
    'collapse': 'Свернуть',
    'view_on_google_maps': 'Открыть в Google Maps',
    'click_to_view': 'Нажмите, чтобы посмотреть местоположение',
    'loading': 'Загрузка...',
    'error': 'Ошибка',
    'success': 'Успешно',
    'save_success': 'Сохранено успешно',
  },
  Arabic: {
    'dashboard': 'لوحة التحكم',
    'log_dive': 'تسجيل الغوص',
    'journal': 'يوميات الغوص',
    'map': 'خريطة المواقع',
    'profile': 'الملف الشخصي',
    'photos': 'الصور',
    'logout': 'تسجيل الخروج',
    'welcome_back': 'مرحباً بعودتك',
    'total_dives': 'إجمالي الغوصات',
    'total_time': 'الوقت الإجمالي تحت الماء',
    'max_depth': 'أقصى عمق',
    'avg_air': 'متوسط استهلاك الهواء',
    'recent_dives': 'أحدث الغوصات',
    'no_dives': 'لا توجد غوصات بعد',
    'log_first_dive': 'سجل غوصتك الأولى',
    'login': 'تسجيل الدخول',
    'register': 'إنشاء حساب',
    'email': 'البريد الإلكتروني',
    'password': 'كلمة المرور',
    'confirm_password': 'تأكيد كلمة المرور',
    'username': 'اسم المستخدم',
    'already_have_account': 'لديك حساب بالفعل؟',
    'no_account': 'ليس لديك حساب؟',
    'login_failed': 'فشل تسجيل الدخول',
    'register_failed': 'فشل إنشاء الحساب',
    'log_dive_title': 'تسجيل غوصة',
    'dive_site': 'موقع الغوص',
    'dive_type': 'نوع الغوص',
    'date': 'التاريخ',
    'buddy': 'الشريك',
    'depth': 'العمق',
    'duration': 'المدة',
    'temperature': 'درجة الحرارة',
    'visibility': 'الرؤية',
    'weight': 'الوزن',
    'notes': 'ملاحظات',
    'rating': 'التقييم',
    'save': 'حفظ',
    'cancel': 'إلغاء',
    'dive_sites': 'مواقع الغوص',
    'view_all': 'عرض الكل',
    'collapse': 'طي',
    'view_on_google_maps': 'فتح في خرائط Google',
    'click_to_view': 'انقر لعرض الموقع',
    'loading': 'جارٍ التحميل...',
    'error': 'خطأ',
    'success': 'نجاح',
    'save_success': 'تم الحفظ بنجاح',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('Chinese');

  useEffect(() => {
    const saved = localStorage.getItem('language') as Language;
    if (saved && ['Chinese','English','French','Spanish','Japanese','German','Russian','Arabic'].includes(saved)) {
      setLanguage(saved);
    }
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const getLanguageName = (lang: Language): string => {
    const found = LANGUAGES.find(l => l.code === lang);
    return found ? found.name : lang;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t, getLanguageName }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
